name: CI

on:
  push:
    branches: 
      - master
      - battle_engine
      - pokemon_expansion
      - item_expansion
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: sudo apt install gcc-arm-none-eabi binutils-arm-none-eabi libcapstone-dev
        # build-essential, git, and libpng-dev are already installed
        # gcc-arm-none-eabi is only needed for the modern build
        # as an alternative to dkP
        # libcapstone-dev is required for inigen

      - name: Install agbcc
        run: |
          git clone https://github.com/pret/agbcc.git
          cd agbcc 
          ./build.sh
          ./install.sh ../

      - name: Agbcc
        run: make -j${nproc} 
